// Generated by scripts/build-iris-ui.mjs from iris-api.mjs. Do not edit; run npm run build:iris.
// Browser backend for the IRIS-served Relay UI (IPM package, /relay/index.html).
// It answers the same API surface as server.mjs (/api/login, /api/password, /api/resource/...,
// /api/manage/..., /api/tasks/..., /api/logs/..., /api/audit/..., /api/explorer/...)
// inside the page, with the same review, re-check, apply-once and read-back logic
// (routes.mjs and the modules it uses), and calls IRIS on the same origin at
// /api/admin and /api/relay as the signed-in operator. No Node.js or Python server.
//
// Credentials: kept in this module's memory only (never in browser storage or
// cookies), sent as HTTP Basic only over HTTPS or to a loopback host, and dropped
// on sign-out or after 30 minutes, which also cancels every request in flight.
// A password change that IRIS requires (routes.mjs changePassword) sends the current
// and the new password once to /api/relay/account, under the same transport rule,
// and keeps only the new one, as the session's credentials.
import {
  changePassword,
  createUpstream,
  PORTAL_PATH,
  route,
  signIn,
  validCredentials,
} from "./routes.js?v=0.5.1";
import { resources } from "./resources.js?v=0.5.1";

export const SESSION_LIFETIME_MS = 30 * 60 * 1000;
export const MAX_INPUT_BYTES = 16000;
const IRIS_BASES = ["/api/admin/", "/api/relay/"];

export const isLoopbackHost = (host) =>
  host === "localhost" ||
  host === "[::1]" ||
  /^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(host);
// HTTP Basic is readable on the wire, so the password only travels over HTTPS,
// or over plain HTTP when the page itself was opened on the IRIS machine.
export const transportAllowed = (loc) =>
  loc.protocol === "https:" ||
  (loc.protocol === "http:" && isLoopbackHost(loc.hostname));
export const TRANSPORT_BLOCKED =
  "Sign-in blocked: this page was opened over plain HTTP on a non-local address, so it will not send your IRIS password. Open it over HTTPS, or on the IRIS machine itself through http://localhost.";

// `extra` carries the reason IRIS gave for a refused sign-in (reason, portal).
const failure = (status, message, extra = {}) =>
  Object.assign(new Error(message), { status, ...extra });

export function createIrisAPI({
  fetcher = (...args) => globalThis.fetch(...args),
  location: loc = globalThis.location,
  now = () => Date.now(),
  onSessionEnd = () => {},
} = {}) {
  const origin = loc.origin;
  let session = null,
    signingIn = null,
    expiry = null,
    failures = { count: 0, until: 0 };

  function end(reason) {
    if (signingIn) signingIn.abort();
    signingIn = null;
    if (!session) return false;
    const ended = session;
    session = null;
    clearTimeout(expiry);
    ended.controller.abort();
    ended.credentials = { username: "", password: "" };
    ended.plans.clear();
    ended.auditJob = null;
    if (reason) onSessionEnd(reason);
    return true;
  }

  // Same-origin IRIS requests only, under /api/admin or /api/relay, and only over
  // an allowed transport; everything else is refused before fetch is called.
  function sessionUpstream(signal) {
    const send = createUpstream({
      fetcher,
      target: origin,
      init: { credentials: "omit", cache: "no-store" },
      signal,
      describeFailures: true,
    });
    return (credentials, path, method, data, base = "/api/admin", timeoutMs, options) => {
      if (!transportAllowed(loc))
        return { ok: false, status: 403, error: TRANSPORT_BLOCKED };
      const url = new URL(base + path, origin);
      if (
        url.origin !== origin ||
        !IRIS_BASES.some((prefix) => url.pathname.startsWith(prefix))
      )
        return {
          ok: false,
          status: 400,
          error: "Relay only calls /api/admin and /api/relay on this IRIS server.",
        };
      return send(credentials, path, method, data, base, timeoutMs, options);
    };
  }

  const failed = () => {
    failures = {
      count: (failures.until > now() ? failures.count : 0) + 1,
      until: now() + 300000,
    };
  };
  // The reason IRIS gave for a refused sign-in, and where the Management Portal
  // (same origin) offers its own password change.
  const refusal = (result) =>
    failure(result.status, result.error, {
      ...(result.reason ? { reason: result.reason } : {}),
      ...(["no-extension", "unknown"].includes(result.reason)
        ? { portal: origin + PORTAL_PATH }
        : {}),
    });

  // Sign-in, or (passwordChange) a password change that IRIS requires followed by a
  // sign-in with the new password. The /api/relay extension comes with this page, so
  // the sign-in check relies on it (relayRequired).
  async function login(input, passwordChange = false) {
    if (!transportAllowed(loc)) throw failure(403, TRANSPORT_BLOCKED);
    if (failures.until > now() && failures.count >= 5)
      throw failure(429, "Too many failed sign-ins. Try again in five minutes.");
    if (!passwordChange && !validCredentials(input))
      throw failure(400, "Enter your IRIS username and password.");
    if (signingIn) throw failure(409, "A sign-in is already in progress.");
    end(null);
    const controller = new AbortController();
    signingIn = controller;
    let credentials = passwordChange
      ? null
      : { username: input.username, password: input.password };
    const upstream = sessionUpstream(controller.signal);
    let signed, changed;
    try {
      if (passwordChange) {
        changed = await changePassword(input, upstream, { relayRequired: true });
        if (changed.status === 200) credentials = changed.credentials;
      }
      if (credentials)
        signed = await signIn(credentials, upstream, { relayRequired: true });
    } finally {
      if (signingIn === controller) signingIn = null;
    }
    if (controller.signal.aborted)
      throw failure(
        401,
        changed?.status === 200
          ? "Sign-in was cancelled after IRIS changed the password. Sign in with the new password."
          : passwordChange
            ? "The password change was cancelled. IRIS may already have changed it: try the new password first."
            : "Sign-in was cancelled.",
      );
    if (changed && changed.status !== 200) {
      if (changed.failed) failed();
      throw refusal(changed);
    }
    if (signed.status !== 200) {
      if (changed)
        throw failure(
          signed.status,
          "IRIS changed the password, but signing in with the new one failed: " + signed.error,
          { passwordChanged: true },
        );
      // A correct password that IRIS wants changed is not a failed guess.
      if (signed.status === 401 && signed.reason !== "password-change-required")
        failed();
      throw refusal(signed);
    }
    failures = { count: 0, until: 0 };
    session = {
      credentials,
      info: signed.info,
      plans: new Map(),
      expires: now() + SESSION_LIFETIME_MS,
      controller,
      upstream,
    };
    expiry = setTimeout(
      () => end("Your Relay session expired after 30 minutes. Sign in again."),
      SESSION_LIFETIME_MS,
    );
    expiry.unref?.();
    return {
      info: signed.info,
      resources,
      server: origin,
      ...(changed ? { passwordChanged: true } : {}),
    };
  }

  async function handle(path, method, data) {
    // A path on this API, never a URL: IRIS requests are built by the routes alone.
    if (typeof path !== "string" || !path.startsWith("/api/"))
      throw failure(404, "Not found.");
    const url = new URL(path, "http://relay.invalid");
    // Mirror the network boundary of the Node server: plain JSON input, bounded size.
    let input = {};
    if (method !== "GET") {
      const raw = JSON.stringify(data ?? {});
      if (new TextEncoder().encode(raw).length > MAX_INPUT_BYTES)
        throw failure(413, "Request too large");
      input = JSON.parse(raw);
    }
    if (url.pathname === "/api/config" && method === "GET")
      return { demo: false, irisServed: true };
    if (url.pathname === "/api/login" && method === "POST") return login(input);
    if (url.pathname === "/api/password" && method === "POST")
      return login(input, true);
    if (!session || session.expires < now()) {
      if (session)
        end("Your Relay session expired after 30 minutes. Sign in again.");
      throw failure(401, "Sign in to your IRIS instance.");
    }
    if (url.pathname === "/api/session" && method === "GET")
      return { info: session.info, resources, server: origin };
    if (url.pathname === "/api/logout" && method === "POST") {
      end(null);
      return { ok: true };
    }
    const current = session;
    const handled = await route(
      {
        method,
        pathname: url.pathname,
        searchParams: url.searchParams,
        readBody: async () => input,
      },
      { session: current, upstream: current.upstream, server: origin },
    );
    if (!handled) throw failure(404, "Not found.");
    if (session !== current)
      throw failure(401, "Signed out. The result was discarded.");
    if (handled.status >= 400)
      throw failure(handled.status, handled.data?.error || "Request failed");
    // A copy, as if it had crossed the network: callers cannot alter stored plans.
    return JSON.parse(JSON.stringify(handled.data));
  }

  const api = async (path, method = "GET", data) => {
    try {
      return await handle(path, method, data);
    } catch (error) {
      if (Number.isInteger(error?.status))
        throw failure(error.status, error.message, {
          ...(typeof error.reason === "string" ? { reason: error.reason } : {}),
          ...(typeof error.portal === "string" ? { portal: error.portal } : {}),
          ...(error.passwordChanged ? { passwordChanged: true } : {}),
        });
      throw failure(
        500,
        "An internal error occurred in the page: " +
          (error?.message || String(error)),
      );
    }
  };
  api.signedIn = () => !!session;
  api.signOut = () => end(null);
  return api;
}
