#!/usr/bin/env node
// Build the full IRIS Relay web UI that IRIS serves from the IPM package (web/relay).
//
// Sources stay where they are: the UI in public/ and the isomorphic logic modules at
// the repository root (the same files server.mjs uses). The build copies them into
// one flat folder with .js names, so any IRIS web server sends a JavaScript MIME
// type, rewrites relative imports to those names with a ?v=<package version> suffix
// (a new release never mixes with cached files of an older one), and makes an
// IRIS variant of index.html (data-mode="iris", a Content-Security-Policy meta tag).
// web/relay/lite.html (Relay Lite) is hand-written and left alone.
//
// Usage: node scripts/build-iris-ui.mjs          write web/relay
//        node scripts/build-iris-ui.mjs --check  exit 1 if web/relay is out of date
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
export const TARGET = "web/relay";
export const HAND_WRITTEN = ["lite.html"];

export const CSP =
  "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'none'; form-action 'self'";

export function packageVersion(root = ROOT) {
  const match = readFileSync(join(root, "module.xml"), "utf8").match(
    /<Version>([0-9]+\.[0-9]+\.[0-9]+)<\/Version>/,
  );
  if (!match) throw new Error("module.xml has no <Version>.");
  return match[1];
}

// Relative module specifiers in from "...", import "..." and import("...").
const SPECIFIER =
  /(\bfrom\s*|\bimport\s*\(\s*|\bimport\s+)(["'])([^"']+)\2/g;

function specifiers(source) {
  return [...source.matchAll(SPECIFIER)].map((m) => m[3]);
}

// The root modules reachable from iris-api.mjs. Anything that is not a sibling
// .mjs (for example node:crypto) would not run in a browser and stops the build.
function rootModules(root) {
  const seen = new Set();
  const visit = (name) => {
    if (seen.has(name)) return;
    seen.add(name);
    const source = readFileSync(join(root, name), "utf8");
    for (const spec of specifiers(source)) {
      const m = spec.match(/^\.\/([A-Za-z0-9_-]+\.mjs)$/);
      if (!m)
        throw new Error(
          `${name} imports ${spec}; browser modules may only import sibling .mjs files.`,
        );
      visit(m[1]);
    }
  };
  visit("iris-api.mjs");
  return [...seen].sort();
}

function rewrite(name, source, map, version) {
  return source.replace(SPECIFIER, (all, lead, quote, spec) => {
    const m = spec.match(/^\.\/([A-Za-z0-9_.-]+)$/);
    const target = m && map.get(m[1]);
    if (!target)
      throw new Error(`${name}: import ${spec} is not part of the IRIS UI.`);
    return `${lead}${quote}./${target}?v=${version}${quote}`;
  });
}

function replaceOnce(text, from, to, file) {
  const count = text.split(from).length - 1;
  if (count !== 1)
    throw new Error(`${file}: expected one "${from}", found ${count}.`);
  return text.replace(from, () => to);
}

function irisIndex(html, version) {
  const steps = [
    ["<!doctype html>\n", "<!doctype html>\n<!-- Generated by scripts/build-iris-ui.mjs from public/index.html. Do not edit; run npm run build:iris. -->\n"],
    ['<html lang="en">', '<html lang="en" data-mode="iris">'],
    [
      '<meta name="viewport" content="width=device-width,initial-scale=1" />\n',
      '<meta name="viewport" content="width=device-width,initial-scale=1" />\n' +
        `    <meta http-equiv="Content-Security-Policy" content="${CSP}" />\n` +
        '    <meta name="referrer" content="no-referrer" />\n' +
        '    <link rel="icon" href="data:," />\n',
    ],
    ['href="./style.css"', `href="./style.css?v=${version}"`],
    ['src="./app.js"', `src="./app.js?v=${version}"`],
    ['<a class="brand" href="./"', '<a class="brand" href="./index.html"'],
    ['<button class="primary" type="submit">', '<button class="primary" type="submit" disabled>'],
    [
      `          <p class="muted">
            Credentials stay in server memory for this session. IRIS permissions
            remain in control.
          </p>`,
      `          <p class="muted">
            Served by IRIS from the iris-relay IPM package, with no Node.js or
            Python server. Your password stays in this page's memory only and
            goes to IRIS as HTTP Basic, only over HTTPS or on the IRIS machine
            itself. Reloading the page signs you out. IRIS permissions remain in
            control.
          </p>
          <p class="muted">
            <a href="./lite.html">Relay Lite</a> is a smaller page with the log
            views and the similarity search only.
          </p>`,
    ],
  ];
  for (const [from, to] of steps) html = replaceOnce(html, from, to, "index.html");
  // IRIS labels static .html and .css files charset=ISO-8859-1, and that header wins
  // over <meta charset>. Plain ASCII with character references reads the same
  // under any charset. (Module scripts are always decoded as UTF-8.)
  return html.replace(
    /[^\x00-\x7f]/gu,
    (c) => "&#x" + c.codePointAt(0).toString(16).toUpperCase() + ";",
  );
}

function asciiOnly(file, text) {
  const at = text.search(/[^\x00-\x7f]/);
  if (at >= 0)
    throw new Error(
      `${file} has a non-ASCII character at offset ${at}; IRIS serves .css as ISO-8859-1, so use a CSS escape such as \\2192.`,
    );
  return true;
}

// Returns Map(published name -> content) for everything the build owns in web/relay.
export function buildIrisUI(root = ROOT) {
  const version = packageVersion(root);
  const modules = rootModules(root);
  const ui = readdirSync(join(root, "public"))
    .filter((n) => /\.(js|css)$/.test(n))
    .sort();
  const map = new Map();
  for (const name of modules) map.set(name, name.replace(/\.mjs$/, ".js"));
  for (const name of ui) {
    if ([...map.values()].includes(name))
      throw new Error(`public/${name} collides with a root module name.`);
    map.set(name, name);
  }
  map.set("iris-api.js", "iris-api.js"); // app.js imports the built name
  const out = new Map();
  for (const name of modules) {
    const source = readFileSync(join(root, name), "utf8");
    out.set(
      map.get(name),
      `// Generated by scripts/build-iris-ui.mjs from ${name}. Do not edit; run npm run build:iris.\n` +
        rewrite(name, source, map, version),
    );
  }
  for (const name of ui) {
    const source = readFileSync(join(root, "public", name), "utf8");
    out.set(
      name,
      name.endsWith(".css")
        ? asciiOnly(`public/${name}`, source) &&
          `/* Generated by scripts/build-iris-ui.mjs from public/${name}. Do not edit; run npm run build:iris. */\n` + source
        : `// Generated by scripts/build-iris-ui.mjs from public/${name}. Do not edit; run npm run build:iris.\n` +
          rewrite(name, source, map, version),
    );
  }
  out.set(
    "index.html",
    irisIndex(readFileSync(join(root, "public", "index.html"), "utf8"), version),
  );
  return out;
}

// Files in web/relay that are neither built nor hand-written.
export function strayFiles(root = ROOT, built = buildIrisUI(root)) {
  return readdirSync(join(root, TARGET)).filter(
    (n) => !built.has(n) && !HAND_WRITTEN.includes(n),
  );
}

export function outdated(root = ROOT) {
  const built = buildIrisUI(root);
  const changed = [];
  for (const [name, content] of built) {
    const path = join(root, TARGET, name);
    if (!existsSync(path) || readFileSync(path, "utf8") !== content)
      changed.push(name);
  }
  return { changed, stray: strayFiles(root, built) };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--check")) {
    const { changed, stray } = outdated();
    if (changed.length || stray.length) {
      console.error(
        `web/relay is out of date. Changed: ${changed.join(", ") || "none"}. Not built: ${stray.join(", ") || "none"}. Run npm run build:iris.`,
      );
      process.exit(1);
    }
    console.log("web/relay is up to date.");
  } else {
    const built = buildIrisUI();
    for (const [name, content] of built)
      writeFileSync(join(ROOT, TARGET, name), content);
    const stray = strayFiles(ROOT, built);
    console.log(
      `Built the IRIS-served UI: ${built.size} files in ${TARGET} (version ${packageVersion()}).` +
        (stray.length ? ` Remove files that are no longer built: ${stray.join(", ")}.` : ""),
    );
    if (stray.length) process.exit(1);
  }
}
